FROM --platform=$TARGETOS/$TARGETARCH alpine:latest AS build
RUN apk -U add alpine-sdk git sudo
RUN adduser -Dh /nsbuild nsbuild && \
    adduser nsbuild abuild && \
    echo 'nsbuild ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nsbuild

USER nsbuild
RUN mkdir -p /nsbuild/src/ /nsbuild/packages/main && \
    abuild-keygen -ain && \
    git clone https://github.com/pg9182/northstar-dedicated.git /tmp/repo && \
    mv /tmp/repo/src /nsbuild/src/main

FROM build AS build-northstar
RUN ulimit -n 1024; cd /nsbuild/src/main/northstar && abuild -r

FROM build AS build-nswrap
RUN ulimit -n 1024; cd /nsbuild/src/main/nswrap && abuild -r

FROM build AS build-entrypoint
RUN ulimit -n 1024; cd /nsbuild/src/main/entrypoint && abuild -r

FROM ghcr.io/inaccuratetank/northstar:wine
RUN --mount=from=build-northstar,source=/nsbuild/packages/main/x86_64,target=/nsbuild/northstar \
    apk add --no-cache --allow-untrusted /nsbuild/northstar/*.apk
RUN --mount=from=build-nswrap,source=/nsbuild/packages/main/x86_64,target=/nsbuild/nswrap \
    --mount=from=build-entrypoint,source=/nsbuild/packages/main/x86_64,target=/nsbuild/entrypoint \
    apk add --no-cache --allow-untrusted /nsbuild/nswrap/*.apk /nsbuild/entrypoint/*.apk
RUN rm -r /nsbuild

# silence Xvfb xkbcomp warnings by working around the bug (present in libX11 1.7.2) fixed in libX11 1.8 by https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/79
RUN echo 'partial xkb_symbols "evdev" {};' > /usr/share/X11/xkb/symbols/inet

RUN adduser -D container && \
    mkdir /mnt/titanfall /mnt/navs && \
    ln /home/container/mods /mnt/mods
USER container
ENV USER=container HOME=/home/container
WORKDIR /home/container

COPY ./entrypoint.sh /entrypoint.sh
CMD ["/bin/sh", "/entrypoint.sh"]